Improve RecurrentComplexTransformer stability.
CrucibleMC/Crucible pull request #89
Opened 2021-12-13 21:55 UTC by Fox2Code

Hi, I'm Fox2Code, I help a Modded network from time to time.
One of the server couldn't start with the latest version of crucible due to `RecurrentComplexTransformer` being unstable. 

So instead to force setting an opcode at a specific index without any check,
I just replace the owner from `joptsimple/internal/Strings` to `io/github/crucible/patches/Hook` if there is a match,
since the name and descriptor are the same there is no need to touch them.

This make the transformer much more stable, as it only apply the patch if needed,
and also remove the instruction index hard-coding, also making the transformer more flexible.

2021-12-15 02:33 UTC, spannerman79 reviewed
Has this been tested against other mods that play around with worldgen?

For example;

- Thaumcraft4
- Team CoFH mods
- Biomes O Plenty (this is one that is "touchy" when it comes to world gen)

Not asking for all mods but I think those are the top three that >90% of modpacks have or do have in them.

2021-12-15 11:03 UTC, Fox2Code commented
This change only affect the RecurrentComplex mod and made on the dev branch of Crucible.
Please go on the files tab to see the changes.

If you think this change could fix compatibility with other mods, please wait for this to be merged before doing your own changes.

2021-12-15 11:23 UTC, drori200 commented
Because of the nature of Crucible, a forge-bukkit hybrid, testing if changes affect some of the big mods is important and should be done in order to prevent more bugs being made in the future

2021-12-15 11:24 UTC, spannerman79 commented
> If you think this change could fix compatibility with other mods, please wait for this to be merged before doing your own changes.

You've got this arse backwards.

Changes made need to be tested **first** against commonly known and used mods that affect world gen.  Now I named prob the most common top ones that would be in the vast number of modpacks.

Test first - then commit. Not the other way around as you state.

2021-12-15 11:34 UTC, Fox2Code commented
The Java ASM library is the library I am the best at, but even worse, you didn't even checked the files tab.

If you would have read these 2 lines you would have know it only affect ReccurentComplex:
```Java
    public void transform(ImagineASM asm) {
        if (asm.is("ivorius.reccomplex.structures.generic.matchers.BiomeMatcher")) {
```
This doesn't even require java knowledge to understand that it doesn't affect anything else.

2021-12-17 17:23 UTC, Fox2Code commented
"enhancement" is not the correct appropriate flag, it's a "bug-fix".

This doesn't add any new functionality, this just fix already existing ones.

2021-12-17 19:07 UTC, drori200 commented
> "enhancement" is not the correct appropriate flag, it's a bug-fix.
> 
> This doesn't add any new functionality, this just fix already existing ones.

This just means it will improve Crucible's state so a bug fix counts as enhancement. Either way don't worry about it

2022-04-03 15:15 UTC, Fox2Code commented
Hi, due to the patch being required to launch some mod-packs on the server I'm working on, for now the server is stuck in an older version of Crucible, can something be done about it? (log4shell exploit is currently being patched with a plugin)

2022-04-03 15:30 UTC, spannerman79 commented
> Hi, due to the patch being required to launch some mod-packs on the server I'm working on, for now the server is stuck in an older version of Crucible, can something be done about it? (log4shell exploit is currently being patched with a plugin)

https://github.com/CrucibleMC/Crucible/releases/tag/v5.3#:~:text=Fix%20for%20CVE,substitution%20is%20enabled.

2022-04-05 17:19 UTC, Fox2Code commented
@spannerman79 the reason why the network can't use the latest version with builtin log4shell patch is in the message.
Is any of the staff in Crucible team know anything about ASM? 
Because it's look like the code is not being merged because the Crucible team doesn't understand it.

2022-04-05 17:24 UTC, juanmuscaria requested changes

2022-04-05 19:26 UTC, Fox2Code commented on src/main/java/io/github/crucible/patches/RecurrentComplexTransformer.java
> +            }
I used your message but replaced `[Crucible] ` with `[Crucible] RecurrentComplexTransformer: `, so it give more context to the users.

2022-04-05 22:30 UTC, juanmuscaria approved these changes

2022-04-05 22:30 UTC, merged